# Generated by Django 5.2.13 on 2026-04-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryquestion',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisoryquestion',
            name='advisor_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advisoryquestion',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisoryquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='advisoryquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
