# Generated by Django 5.2.13 on 2026-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_nepali', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('read_time', models.CharField(blank=True, max_length=50)),
                ('published_label', models.CharField(blank=True, max_length=50)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
